# Generated by Django 2.2.6 on 2019-10-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemap', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('heroname', models.CharField(max_length=20)),
                ('herolife', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('herolevel', models.IntegerField()),
                ('herogender', models.BooleanField()),
                ('password', models.CharField(max_length=20)),
                ('herobody', models.CharField(max_length=20)),
                ('hero_x', models.FloatField()),
                ('hero_y', models.FloatField()),
                ('loginlabel', models.BooleanField()),
                ('imagemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameMap')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponname', models.CharField(max_length=50)),
                ('weapon_x', models.IntegerField()),
                ('weapon_y', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=50)),
                ('skill_x', models.IntegerField()),
                ('skill_y', models.IntegerField()),
                ('derection', models.CharField(max_length=20)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monstername', models.CharField(max_length=20)),
                ('monsterlife', models.IntegerField()),
                ('monsterfire', models.CharField(max_length=20)),
                ('monsterbody', models.CharField(max_length=20)),
                ('monster_x', models.FloatField()),
                ('monster_y', models.FloatField()),
                ('imagemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameMap')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homebuild', models.CharField(max_length=50)),
                ('homebuild_x', models.IntegerField()),
                ('homebuild_y', models.IntegerField()),
                ('homewidth', models.IntegerField()),
                ('homeheight', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField()),
                ('content', models.CharField(max_length=30)),
                ('label', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildname', models.CharField(max_length=50)),
                ('build_x', models.IntegerField()),
                ('build_y', models.IntegerField()),
                ('build_height', models.IntegerField()),
                ('build_width', models.IntegerField()),
                ('buildmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameMap')),
            ],
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bossname', models.CharField(max_length=20)),
                ('bosslife', models.IntegerField()),
                ('bossfire', models.IntegerField()),
                ('bossthings', models.CharField(max_length=20)),
                ('boss_x', models.FloatField()),
                ('boss_y', models.FloatField()),
                ('bossmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameMap')),
            ],
        ),
    ]
