# Generated by Django 2.2.5 on 2019-10-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemap', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroname', models.CharField(max_length=20)),
                ('herolife', models.IntegerField()),
                ('herolevel', models.IntegerField()),
                ('herofire', models.CharField(max_length=20)),
                ('herobody', models.CharField(max_length=20)),
                ('hero_x', models.IntegerField()),
                ('hero_y', models.IntegerField()),
                ('imagemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameMap')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('heroname', models.CharField(max_length=20)),
                ('herolife', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('herolevel', models.IntegerField()),
                ('herogender', models.BooleanField()),
                ('password', models.CharField(max_length=20)),
                ('herofire', models.CharField(max_length=20)),
                ('herobody', models.CharField(max_length=20)),
                ('hero_x', models.IntegerField()),
                ('hero_y', models.IntegerField()),
                ('imagemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameMap')),
            ],
        ),
    ]
