# Generated by Django 2.2.6 on 2019-10-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
